# Generated by Django 2.1.7 on 2019-02-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Status', models.TextField(blank=True, null=True)),
                ('Completed', models.BooleanField()),
            ],
        ),
    ]
