# Generated by Django 2.1.7 on 2019-03-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Todo', models.CharField(max_length=128)),
                ('Description', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='To_do_list',
        ),
    ]
