# Generated by Django 2.1.7 on 2019-03-07 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monthlygoals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Status',
            new_name='Deadline',
        ),
    ]
